# Setup
title: 滔滔
description: "Make it fun, not just do fun things."
url: https://wuoody.icu
avatar: /my-avatar.jpg
paginate: 5
permalink: pretty
cover_image: /mybg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: asdsadsadasd
  card: summary
logo: logo.png
social:
  name: Wuoody Wu
  links:
    - https://twitter.com/123
    - https://github.com/WuDi329
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Wuoody Wu
  url: https://github.com/WuDi329
  email: diiiwuuu@gmail.com
